import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";

const llm = new ChatGoogleGenerativeAI({
  model: "gemini-1.5-flash",
  apiKey: process.env.GEMINI_API_KEY,
  temperature: 0.5,
});

const MANAGER_SYSTEM_PROMPT = `You are a senior investment analyst and report writer.
You receive structured data from three specialist agents (Financial, SWOT, Competitor) and compile a comprehensive startup investment analysis report in Markdown format.

The report MUST have exactly these 5 sections:

# {Startup Name} — Investment Analysis Report

## 1. Executive Summary
A 3-5 sentence overview: what the startup does, their stage, key highlights, and overall investment thesis.

## 2. Financial Overview
Present the funding history, investors, revenue, valuation, and business model. Use bullet points.

## 3. SWOT Analysis
Present strengths, weaknesses, opportunities, and threats clearly. Use bullet points under each sub-heading.

## 4. Competitive Landscape
Name the market category, describe the market, list key competitors with their funding and differentiators. Use a markdown table if possible.

## 5. Investment Recommendation
State clearly: **Bullish** / **Neutral** / **Bearish**
Provide 3-5 bullet points of reasoning for the recommendation.

---
*Report generated by Multi-Agent Startup Analyser*

Be professional, concise, and data-driven. Do NOT add any sections beyond the 5 listed above.`;

export async function runManagerAgent(
  startupName: string,
  financialData: object,
  swotData: object,
  competitorData: object
): Promise<string> {
  const agentDataSummary = `
FINANCIAL AGENT OUTPUT:
${JSON.stringify(financialData, null, 2)}

SWOT AGENT OUTPUT:
${JSON.stringify(swotData, null, 2)}

COMPETITOR AGENT OUTPUT:
${JSON.stringify(competitorData, null, 2)}
`;

  const messages = [
    new SystemMessage(MANAGER_SYSTEM_PROMPT),
    new HumanMessage(
      `Compile a full investment analysis report for: "${startupName}".\n\nHere is the data gathered by the specialist agents:\n${agentDataSummary}`
    ),
  ];

  const response = await llm.invoke(messages);
  return response.content as string;
}
